import { TemplateId } from './index';

export const defaultTemplatesData: Record<TemplateId, Record<string, any>> = {
  '1-a': {
    headerLine1: "TU VERSES LE LIQUIDE VITE",
    headerLine2: "2 MINUTES? TU ES FAIBLE?",
    subjectImage: "/templates/assets/PATSIMMSCFLYER7.png",
    productImage: "/templates/assets/30.png",
    priceBadgeText: "PRIX 5.000F(10$)",
    footerLine1: "LIS LA METHODE ET APPLIQUES",
    footerLine2: "PAS BESOIN DE FAIRE LE SPORT",
  },
  '1-b': {
    topBackgroundImage: "/templates/assets/PATSIMMSCFLYER1.png",
    productImage: "/templates/assets/30.png",
    priceBadgeText: "PRIX 5.000F(10$)",
    title: "2 MINUTES AU LIT",
    subtitle: "C'EST RIDICULE",
    bodyParagraph: "Découvrez la méthode naturelle pour durer plus longtemps au lit sans aucun effet secondaire ni produit chimique.",
    footerText: "CA MARCHE SANS PRODUIT",
  },
  '2-a': {
    backgroundImage: "/templates/assets/Screenshot_20260615-144511.jpg",
    logoUrl: "",
    logoPosition: "left",
    hasAvatar: false,
    avatarUrl: "/templates/assets/images.jpeg",
    headline: "ZUCKERBERG ADMITS [META MADE] [MISTAKES] DURING AI RESTRUCTURING",
    highlightColor: "#E50914",
  },
  '3-a': {
    backgroundImage: "/templates/assets/Screenshot_20260615-144802.jpg",
    productImage: "/templates/assets/30.png",
    headline: "THIS IS MY #1 TOOL TO SCALE BRANDS",
    badgeText: "OFFRE EXCLUSIVE",
  },
  '3-b': {
    backgroundImage: "/templates/assets/Screenshot_20260615-144618.jpg",
    postAuthor: "Cybernews Tech",
    postHandle: "@cybernews",
    postAvatar: "/templates/assets/images_1.jpeg",
    postContent: "Meta removes facial recognition code from smart glasses app after widespread privacy backlash.",
    postStats: "14.2k Likes • 3.4k Reposts",
  },
  '4-a': {
    headerTitle: "RECRUTEMENT TELEVENTE",
    bodyImage: "/templates/assets/Copie_de_AFFICHE_RECRUTEMENT_CALL_CENTER_.png",
    flagBadgeUrl: "",
    footerSalary: "SALAIRE DE BASE: 80.000 F CFA",
    footerCommissions: "+ COMMISSIONS DEPLAFONNEES",
  },
  '5-a': {
    backgroundColor: "#55B23B",
    title: "DOUBLER VOS VENTES EN 90 JOURS",
    subtitle: "(SANS PAYER PLUS DE PUBLICITÉ)",
    emoji: "👇",
  },
  'custom': {
    canvasBgColor: "#0f172a",
    layers: [
      {
        id: 'layer-bg-accent',
        type: 'shape',
        name: 'Background Accent',
        left: 60,
        top: 60,
        width: 960,
        height: 960,
        zIndex: 1,
        backgroundColor: '#1e293b',
        borderRadius: 24,
        borderWidth: 2,
        borderColor: '#334155',
      },
      {
        id: 'layer-headline',
        type: 'text',
        name: 'Headline',
        left: 120,
        top: 140,
        width: 840,
        height: 120,
        zIndex: 10,
        text: 'CREATE HIGH-CONVERTING STATIC ADS',
        color: '#FFFFFF',
        fontSize: 48,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'layer-subhead',
        type: 'text',
        name: 'Sub-headline',
        left: 140,
        top: 280,
        width: 800,
        height: 80,
        zIndex: 10,
        text: 'AI-Powered Layouts & Direct-Response Design System',
        color: '#94a3b8',
        fontSize: 28,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'layer-image',
        type: 'image',
        name: 'Product Mockup',
        left: 290,
        top: 400,
        width: 500,
        height: 420,
        zIndex: 5,
        imageUrl: '/templates/assets/30.png',
        borderRadius: 16,
      },
      {
        id: 'layer-badge',
        type: 'text',
        name: 'Call to Action',
        left: 340,
        top: 860,
        width: 400,
        height: 70,
        zIndex: 15,
        text: 'EXPLORE TEMPLATES >',
        color: '#0f172a',
        textBackgroundColor: '#38bdf8',
        fontSize: 22,
        fontWeight: 'bold',
        textAlign: 'center',
        borderRadius: 35,
      }
    ]
  }
};
